version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ai_tools_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ai_tools
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/database/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped

  backend:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: ai_tools_backend
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=ai_tools
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: ai_tools_frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data: 